# Mimicing Kirkby's speclite travis file
#
# We set the language to c because python isn't supported on the MacOS X nodes
# on Travis. However, the language ends up being irrelevant anyway, since we
# install Python ourselves using conda.
language: c

os:
    - linux

# Setting sudo to false opts in to Travis-CI container-based builds.
sudo: false

# The apt packages below are needed for sphinx builds, which can no longer
# be installed with sudo apt-get.
addons:
    apt:
        packages:
            - graphviz
            - texlive-latex-extra
            - dvipng
            - libgsl0-dev

env:
    global:

        # The following versions are the 'default' for tests, unless
        # overridden underneath. They are defined here in order to save having
        # to repeat them for all configurations.
        - FOLDERNAME='pypeit'
        - PYTHON_VERSION=3.7
        - ASTROPY_VERSION=stable
        - NUMPY_VERSION=stable

        # Conda packages for affiliated packages are hosted in channel
        # "astropy" while builds for astropy LTS with recent numpy versions
        # are in astropy-ci-extras. If your package uses either of these,
        # add the channels to CONDA_CHANNELS along with any other channels
        # you want to use.
        - CONDA_CHANNELS='astropy-ci-extras conda-forge anaconda conda-forge/label/gcc7'

    matrix:
        - PYTHON_VERSION=3.7 SETUP_CMD='egg_info'



matrix:

    # Don't wait for allowed failures
    fast_finish: true

        # Do a PEP8 test with pycodestyle
        - os: linux
          env: MAIN_CMD='pycodestyle packagename --count' SETUP_CMD=''

    include:
        # Try numpy 1.18
        - os: linux
          env: NUMPY_VERSION=1.18
        # Try numpy 1.19
        - os: linux
          env: NUMPY_VERSION=1.19

    allow_failures:
        # Do a PEP8 test with pycodestyle
        # (allow to fail unless your code completely compliant)
        - os: linux
        env: MAIN_CMD='pycodestyle packagename --count' SETUP_CMD=''


install:

    - git clone git://github.com/astropy/ci-helpers.git
    - source ci-helpers/travis/setup_conda_$TRAVIS_OS_NAME.sh

script:

    - pytest
