#!/bin/bash

cd doc
make clean; make html
cd ../
git add doc/*.rst

printf "Now check the modified files with:\n\n    git status\n\nAnd commit the changes with: \n\n   git commit -m 'updated docs'\n\n"

exit 0
